### ISSUE TITLE
Custom extensions not reachable after registration

### ISSUE THREAD

**Issue by domideimel** [vuestorefront/vue-storefront-api#481]
I wrote an extension for the vue-storefront-api that allows me to get and process my custom index for dynamic menus.
I created a folder in `/src/api/extensions/` and in this folder is my extension specific code and extended the the config for vue-storefront-api to know about my extension.
When initializing the API in dev-mode the console output says that all extensions including mine are properly loaded and can be reached under `/ext/<extension-name>`. The problem I'm faceing is that neither one of the extensions can be reached!

I already eliminated the reverse-proxy on my dev-vm. I tried to reach the endpoint via curl directly from my dev-vm. I tried another path for all extensions and even put them on the root-url-level of the api. No matter what i do I always get a 404 back. All theses extension-urls are not reachable because they unfortunately don't exist.
All extensions are registered in this for of loop: https://github.com/DivanteLtd/vue-storefront-api/blob/7c2cf9b845fe93f761f3fb526d48e689a3afc42a/src/api/index.ts#L49
I think the loop may cause the problem.

I did a little resarch and found [this Stackoverlfow post](https://stackoverflow.com/questions/33986989/can-routes-in-express-be-declared-with-a-loop) but the switch to a foreach instead of a for-of-loop gets the same result - a 404 on the requested route.

**Comment by grimasod** [comment]
Try:
`/api/ext/<extension-name>/<action>`
